---
title: "Muhammad Niam Makhali's CV"
author: Muhammad Niam Makhali
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "cv_data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _sg17-17.github.io/myportofolio/cv.html_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```

Language {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```

Core Competencies {#core}
--------------------------------------------------------------------------------

```{r}
CV <- print_text_block(CV, 'core_competencies_aside')
```

Certifications {#certs}
--------------------------------------------------------------------------------

```{r}
CV <- print_text_block(CV, 'certifications_aside')
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**datadrivencv**](https://github.com/nstrayer/datadrivencv). 

Last updated on `r Sys.Date()`.


Main
================================================================================

Muhammad Niam Makhali {#title}
--------------------------------------------------------------------------------

```{r}
CV <- print_text_block(CV, "intro") 
```


Education {data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```


Professional Experience
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'professional_experience')
```


Research & Survey Experience
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'research_experience')
```

Publications
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'publications')
```

```{r}
print_links(CV)
```
